vim-asciidoc
------------

__Enhanced editing support for http://asciidoc.org[Asciidoc] files in
Vim__

Dependencies
~~~~~~~~~~~~

* https://github.com/tomtom/tlib_vim[]
* https://github.com/dahu/Asif[]
* https://github.com/vim-scripts/SyntaxRange[]

Lists
~~~~~

Nested bullet and number lists are supported using the following syntax:
----
* item
** sub-item
*** sub-sub-item
----

And numbered lists:
----
. item
.. sub-item
... sub-sub-item
----

Reformatting
~~~~~~~~~~~~

By default, Vim does the wrong thing by reformatting Asciidoc's block
delimiters as part of the paragraph. The vim-asciidoc plugin fixes
that problem, correctly formatting blocks, lists and normal
paragraphs.

NOTE: This is a work in progress and not all things work as expected
yet.

vim-asciidoc also provides better reformatting of lists.

Syntax Highlighting
~~~~~~~~~~~~~~~~~~~

vim-asciidoc merely bundles Stuart Rackham's original asciidoc syntax
file.

If you have the
https://github.com/vim-scripts/SyntaxRange[SyntaxRange] plugin
installed, source blocks within ++[=+-]++ blocks will be highlighted
according to the named language. Currently only C, Python and VimL are
highlighted by default. Submit a PR if you want to extend this set, or just
add your own to ++~/.vim/after/syntax/asciidoc.vim++

Snippets
~~~~~~~~

vim-asciidoc provides several convenient snippets in the
https://github.com/garbas/vim-snipmate[snipmate] format.
